package com.hibernate;
// Generated 2017-5-31 16:45:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Hdata generated by hbm2java
 */
public class Hdata implements java.io.Serializable {

	private Integer id;
	private int sensorId;
	private String sinkId;
	private String name;
	private Integer typeId;
	private Date dataTime;
	private String value;

	public Hdata() {
	}

	public Hdata(int sensorId, String sinkId, Date dataTime) {
		this.sensorId = sensorId;
		this.sinkId = sinkId;
		this.dataTime = dataTime;
	}

	public Hdata(int sensorId, String sinkId, String name, Integer typeId, Date dataTime, String value) {
		this.sensorId = sensorId;
		this.sinkId = sinkId;
		this.name = name;
		this.typeId = typeId;
		this.dataTime = dataTime;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSensorId() {
		return this.sensorId;
	}

	public void setSensorId(int sensorId) {
		this.sensorId = sensorId;
	}

	public String getSinkId() {
		return this.sinkId;
	}

	public void setSinkId(String sinkId) {
		this.sinkId = sinkId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public Date getDataTime() {
		return this.dataTime;
	}

	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
