package com.hibernate;
// default package
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

/**
 * Pushreg generated by hbm2java
 */
public class Pushreg implements java.io.Serializable {

	private Integer id;
	private User user;
	private String regId;

	public Pushreg() {
	}

	public Pushreg(User user) {
		this.user = user;
	}

	public Pushreg(User user, String regId) {
		this.user = user;
		this.regId = regId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRegId() {
		return this.regId;
	}

	public void setRegId(String regId) {
		this.regId = regId;
	}

}
