package com.hibernate;
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

/**
 * Pushstate generated by hbm2java
 */
public class Pushstate implements java.io.Serializable {

	private String id;

	public Pushstate() {
	}

	public Pushstate(String id) {
		this.id = id;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
