package com.hibernate;
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sink generated by hbm2java
 */
public class Sink implements java.io.Serializable, com.base.DefinedJSONObject {

	private String id;
	private User user;
	private String name;
	private BigDecimal longitude;
	private BigDecimal latitude;
	private Set sensors = new HashSet(0);

	public Sink() {
	}

	public Sink(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Sink(String id, User user, String name, BigDecimal longitude, BigDecimal latitude, Set sensors) {
		this.id = id;
		this.user = user;
		this.name = name;
		this.longitude = longitude;
		this.latitude = latitude;
		this.sensors = sensors;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public Set getSensors() {
		return this.sensors;
	}

	public void setSensors(Set sensors) {
		this.sensors = sensors;
	}
	
	public String toJSONString(){
		String str = "{";
		str += "id:'"+id+"',";
		str += "user:"+user.toJSONString()+",";
		str += "name:'"+name+"',";
		str += "longitude:'"+longitude.toString()+"',";
		str += "latitude:'"+latitude.toString()+"'";
		str += "}";
		return str;
	}
}
