package com.hibernate;
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import com.base.DefinedJSONObject;

/**
 * Subscription generated by hbm2java
 */
public class Subscription implements java.io.Serializable, DefinedJSONObject {

	private Integer id;
	private Sink sink;
	private Sensor sensor;
	private User user;
	private Date subTime;
	private Integer sendFrequency;
	private String address;
	private int filter;
	private Float thresholdValue;

	public Subscription() {
	}

	public Subscription(Sensor sensor, User user, Date subTime, String address, int filter) {
		this.sensor = sensor;
		this.user = user;
		this.subTime = subTime;
		this.address = address;
		this.filter = filter;
	}

	public Subscription(Sensor sensor, User user, Date subTime, Integer sendFrequency, String address, int filter,
			Float thresholdValue) {
		this.sensor = sensor;
		this.user = user;
		this.subTime = subTime;
		this.sendFrequency = sendFrequency;
		this.address = address;
		this.filter = filter;
		this.thresholdValue = thresholdValue;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getSubTime() {
		return this.subTime;
	}

	public void setSubTime(Date subTime) {
		this.subTime = subTime;
	}

	public Integer getSendFrequency() {
		return this.sendFrequency;
	}

	public void setSendFrequency(Integer sendFrequency) {
		this.sendFrequency = sendFrequency;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getFilter() {
		return this.filter;
	}

	public void setFilter(int filter) {
		this.filter = filter;
	}

	public Float getThresholdValue() {
		return this.thresholdValue;
	}

	public void setThresholdValue(Float thresholdValue) {
		this.thresholdValue = thresholdValue;
	}

	public String toJSONString() {
		// TODO Auto-generated method stub
		String result = "{";
		result += "id:'"+id+"',";
		result += "sensor:"+(sensor.toJSONString())+",";
		result += "user:"+(user.toJSONString())+",";
		result += "sub_time:'"+subTime+"',";
		result += "}";
		
		return result;
	}

}
