package com.hibernate;
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SubViewId generated by hbm2java
 */
public class SubViewId implements java.io.Serializable {

	private String id;
	private String userId;
	private Integer sendFrequency;
	private String address;
	private int filter;
	private Float thresholdValue;
	private String regId;
	private String sensorId;
	private String sensorName;
	private Date dataTime;
	private String sensorValue;
	private String typeName;

	public SubViewId() {
	}

	public SubViewId(String userId, String address, int filter, String sensorId, String sensorName, Date dataTime,
			String typeName) {
		this.userId = userId;
		this.address = address;
		this.filter = filter;
		this.sensorId = sensorId;
		this.sensorName = sensorName;
		this.dataTime = dataTime;
		this.typeName = typeName;
	}

	public SubViewId(String id, String userId, Integer sendFrequency, String address, int filter, Float thresholdValue,
			String regId, String sensorId, String sensorName, Date dataTime, String sensorValue, String typeName) {
		this.id = id;
		this.userId = userId;
		this.sendFrequency = sendFrequency;
		this.address = address;
		this.filter = filter;
		this.thresholdValue = thresholdValue;
		this.regId = regId;
		this.sensorId = sensorId;
		this.sensorName = sensorName;
		this.dataTime = dataTime;
		this.sensorValue = sensorValue;
		this.typeName = typeName;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getSendFrequency() {
		return this.sendFrequency;
	}

	public void setSendFrequency(Integer sendFrequency) {
		this.sendFrequency = sendFrequency;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getFilter() {
		return this.filter;
	}

	public void setFilter(int filter) {
		this.filter = filter;
	}

	public Float getThresholdValue() {
		return this.thresholdValue;
	}

	public void setThresholdValue(Float thresholdValue) {
		this.thresholdValue = thresholdValue;
	}

	public String getRegId() {
		return this.regId;
	}

	public void setRegId(String regId) {
		this.regId = regId;
	}

	public String getSensorId() {
		return this.sensorId;
	}

	public void setSensorId(String sensorId) {
		this.sensorId = sensorId;
	}

	public String getSensorName() {
		return this.sensorName;
	}

	public void setSensorName(String sensorName) {
		this.sensorName = sensorName;
	}

	public Date getDataTime() {
		return this.dataTime;
	}

	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	public String getSensorValue() {
		return this.sensorValue;
	}

	public void setSensorValue(String sensorValue) {
		this.sensorValue = sensorValue;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubViewId))
			return false;
		SubViewId castOther = (SubViewId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getSendFrequency() == castOther.getSendFrequency())
						|| (this.getSendFrequency() != null && castOther.getSendFrequency() != null
								&& this.getSendFrequency().equals(castOther.getSendFrequency())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& (this.getFilter() == castOther.getFilter())
				&& ((this.getThresholdValue() == castOther.getThresholdValue())
						|| (this.getThresholdValue() != null && castOther.getThresholdValue() != null
								&& this.getThresholdValue().equals(castOther.getThresholdValue())))
				&& ((this.getRegId() == castOther.getRegId()) || (this.getRegId() != null
						&& castOther.getRegId() != null && this.getRegId().equals(castOther.getRegId())))
				&& ((this.getSensorId() == castOther.getSensorId()) || (this.getSensorId() != null
						&& castOther.getSensorId() != null && this.getSensorId().equals(castOther.getSensorId())))
				&& ((this.getSensorName() == castOther.getSensorName()) || (this.getSensorName() != null
						&& castOther.getSensorName() != null && this.getSensorName().equals(castOther.getSensorName())))
				&& ((this.getDataTime() == castOther.getDataTime()) || (this.getDataTime() != null
						&& castOther.getDataTime() != null && this.getDataTime().equals(castOther.getDataTime())))
				&& ((this.getSensorValue() == castOther.getSensorValue())
						|| (this.getSensorValue() != null && castOther.getSensorValue() != null
								&& this.getSensorValue().equals(castOther.getSensorValue())))
				&& ((this.getTypeName() == castOther.getTypeName()) || (this.getTypeName() != null
						&& castOther.getTypeName() != null && this.getTypeName().equals(castOther.getTypeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getSendFrequency() == null ? 0 : this.getSendFrequency().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + this.getFilter();
		result = 37 * result + (getThresholdValue() == null ? 0 : this.getThresholdValue().hashCode());
		result = 37 * result + (getRegId() == null ? 0 : this.getRegId().hashCode());
		result = 37 * result + (getSensorId() == null ? 0 : this.getSensorId().hashCode());
		result = 37 * result + (getSensorName() == null ? 0 : this.getSensorName().hashCode());
		result = 37 * result + (getDataTime() == null ? 0 : this.getDataTime().hashCode());
		result = 37 * result + (getSensorValue() == null ? 0 : this.getSensorValue().hashCode());
		result = 37 * result + (getTypeName() == null ? 0 : this.getTypeName().hashCode());
		return result;
	}

}
