package com.hibernate;
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

/**
 * SubView generated by hbm2java
 */
public class SubView implements java.io.Serializable {

	private SubViewId id;

	public SubView() {
	}

	public SubView(SubViewId id) {
		this.id = id;
	}

	public SubViewId getId() {
		return this.id;
	}

	public void setId(SubViewId id) {
		this.id = id;
	}

}
