package com.hibernate;
// Generated 2016-12-30 13:34:40 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private Integer id;
	private String name;
	private String unitSymbol;
	private Set sensors = new HashSet(0);

	public Type() {
	}

	public Type(String name, String unitSymbol) {
		this.name = name;
		this.unitSymbol = unitSymbol;
	}

	public Type(String name, String unitSymbol, Set sensors) {
		this.name = name;
		this.unitSymbol = unitSymbol;
		this.sensors = sensors;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUnitSymbol() {
		return this.unitSymbol;
	}

	public void setUnitSymbol(String unitSymbol) {
		this.unitSymbol = unitSymbol;
	}

	public Set getSensors() {
		return this.sensors;
	}

	public void setSensors(Set sensors) {
		this.sensors = sensors;
	}

	public String toJSONString(){
		String str = name;
		return str;
	}
}
