package com.hibernate;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String id;
	private String password;
	private String email;
	private String regTime;
	private boolean poster;
	private Set subscriptions = new HashSet(0);
	private Set pushregs = new HashSet(0);
	private Set sinks = new HashSet(0);

	public User() {
	}

	public User(String id, String password, String regTime, boolean poster) {
		this.id = id;
		this.password = password;
		this.regTime = regTime;
		this.poster = poster;
	}

	public User(String id, String password, String email, String regTime, boolean poster, Set subscriptions,
			Set pushregs, Set sinks) {
		this.id = id;
		this.password = password;
		this.email = email;
		this.regTime = regTime;
		this.poster = poster;
		this.subscriptions = subscriptions;
		this.pushregs = pushregs;
		this.sinks = sinks;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRegTime() {
		return this.regTime;
	}

	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}

	public boolean isPoster() {
		return this.poster;
	}

	public void setPoster(boolean poster) {
		this.poster = poster;
	}

	public Set getSubscriptions() {
		return this.subscriptions;
	}

	public void setSubscriptions(Set subscriptions) {
		this.subscriptions = subscriptions;
	}

	public Set getPushregs() {
		return this.pushregs;
	}

	public void setPushregs(Set pushregs) {
		this.pushregs = pushregs;
	}

	public Set getSinks() {
		return this.sinks;
	}

	public void setSinks(Set sinks) {
		this.sinks = sinks;
	}
	
	public String toJSONString(){
		return String.format("{id:'%s',pwd:'%s',email:'%s',regTime:'%s',poster:'%b'}",id,password,email,regTime,poster);
	}
}
